PRESET_BASE: 'mainnet'
CONFIG_NAME: 'testnet'

# Transition
# ---------------------------------------------------------------
TERMINAL_TOTAL_DIFFICULTY: 0
TERMINAL_BLOCK_HASH: 0x1d9faa205f57d9b068fb41845cdebcea9275f746e96ec62751e2a47f66fa60d8
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0

# Genesis
# ---------------------------------------------------------------
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 64
MIN_GENESIS_TIME: 1680332778
GENESIS_FORK_VERSION: 0x00677693
GENESIS_DELAY: 60
ALTAIR_FORK_VERSION: 0x01677693
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_VERSION: 0x02677693
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_VERSION: 0x03677693
CAPELLA_FORK_EPOCH: 18446744073709551615

# Time parameters
# ---------------------------------------------------------------
SECONDS_PER_SLOT: 12
SECONDS_PER_ETH1_BLOCK: 6
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
SHARD_COMMITTEE_PERIOD: 256
ETH1_FOLLOW_DISTANCE: 5
SLOTS_PER_EPOCH: 6
EPOCHS_PER_ETH1_VOTING_PERIOD: 2

# Validator cycle
# ---------------------------------------------------------------
INACTIVITY_SCORE_BIAS: 4
INACTIVITY_SCORE_RECOVERY_RATE: 16
EJECTION_BALANCE: 16000000000
MIN_PER_EPOCH_CHURN_LIMIT: 4
CHURN_LIMIT_QUOTIENT: 65536
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
DEPOSIT_CHAIN_ID: 1881
DEPOSIT_NETWORK_ID: 1881
DEPOSIT_CONTRACT_ADDRESS: 0x4242424242424242424242424242424242424242
